name: CI Build
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: go get -t ./...

      - name: golangci-lint
        run: |
          curl -sfSL -o install.sh https://raw.githubusercontent.com/golangci/golangci-lint/v1.42.1/install.sh
          echo "0762a15cd7ac4ef439cdfb63bf12865b53c03543c0981b5d46fb542497238b829a33334a288c09d356ec8f797804dfed56f687cbcffcf853ff93da6da4106736 install.sh" | sha512sum -c
          sh ./install.sh -b $(go env GOPATH)/bin v1.42.1
          ~/go/bin/golangci-lint run

      - name: Create credentials file
        run: |
          mkdir ~/.release-droid/
          echo 'github_oauth_access_token=${{ secrets.EXA_CI_2_TOKEN_FOR_UNIFYING_ISSUE_LABELS }}' > ~/.release-droid/credentials

      - name: test
        run: go test -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
