name: CI Build
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: go get -t ./...

      - name: golangci-lint
        run: ci/install_and_run_golangci-lint.sh

      - name: Create credentials file
        run: |
          mkdir ~/.release-droid/
          echo 'github_oauth_access_token=${{ secrets.EXA_CI_2_TOKEN_FOR_UNIFYING_ISSUE_LABELS }}' > ~/.release-droid/credentials

      - name: test
        run: go test -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
